# Generated by Django 2.0.5 on 2019-04-03 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('maincalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('student_number', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=10)),
                ('position', models.CharField(default='', max_length=100)),
                ('organization', models.CharField(default='', max_length=100)),
                ('org_acronym', models.CharField(default='', max_length=10)),
                ('college', models.CharField(choices=[('1', 'College of Engineering'), ('2', 'College of Science')], default='', max_length=100)),
                ('degree_program', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmarked', to='maincalendar.Event')),
            ],
        ),
    ]
