# Generated by Django 2.1 on 2019-03-22 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('student_number', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=10)),
                ('position', models.CharField(default='', max_length=100)),
                ('organization', models.CharField(default='', max_length=100)),
                ('org_acronym', models.CharField(default='', max_length=10)),
                ('degree_program', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
