# Generated by Django 2.0.5 on 2019-03-21 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_start', models.DateField(default=django.utils.timezone.now)),
                ('date_end', models.DateField(default=django.utils.timezone.now)),
                ('time_start', models.TimeField(blank=True, default=None, null=True)),
                ('time_end', models.TimeField(blank=True, default=None, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('seminar', 'SEMINAR'), ('workshop', 'WORKSHOP'), ('convention', 'CONVENTION'), ('review session', 'REVIEW SESSION'), ("applicants' orientation", "APPLICANTS' ORIENTATION"), ('competition', 'COMPETITION'), ('outreach', 'OUTREACH'), ('fundraising', 'FUNDRAISING'), ('others', 'OTHERS')], default=None, max_length=100, null=True)),
                ('venue', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('scope', models.CharField(blank=True, choices=[('program-restricted', 'PROGRAM-RESTRICTED'), ('college-restricted', 'COLLEGE-RESTRICTED'), ('university-wide', 'UNIVERSITY-WIDE'), ('open to all', 'OPEN TO ALL')], default=None, max_length=50, null=True)),
                ('limit', models.IntegerField(blank=True, default=None, null=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='maincalendar.Event'),
        ),
    ]
