# Generated by Django 2.1.5 on 2019-04-05 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincalendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='scope',
        ),
        migrations.AddField(
            model_name='announcement',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='college',
            field=models.CharField(blank=True, choices=[('1', 'College of Engineering'), ('2', 'College of Science')], default='N/A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deg_prog',
            field=models.CharField(blank=True, choices=[('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Computer Engineering', 'Computer Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics Engineering', 'Electronics Engineering'), ('Geodetic Engineering', 'Geodetic Engineering'), ('Industrial Engineering', 'Industrial Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Mining Engineering', 'Mining Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering'), ('Materials Engineering', 'Materials Engineering')], default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Seminar', 'SEMINAR'), ('Workshop', 'WORKSHOP'), ('Convention', 'CONVENTION'), ('Review Session', 'REVIEW SESSION'), ("Applicants' Orientation", "APPLICANTS' ORIENTATION"), ('Competition', 'COMPETITION'), ('Outreach', 'OUTREACH'), ('Fundraising', 'FUNDRAISING'), ('Others', 'OTHERS')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
