# Generated by Django 2.0.5 on 2019-02-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincalendar', '0002_auto_20190206_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('seminar', 'SEMINAR'), ('workshop', 'WORKSHOP'), ('convention', 'CONVENTION'), ('review session', 'REVIEW SESSION'), ("applicants' orientation", "APPLICANTS' ORIENTATION"), ('competition', 'COMPETITION'), ('outreach', 'OUTREACH'), ('fundraising', 'FUNDRAISING'), ('others', 'OTHERS')], default=None, max_length=100, null=True),
        ),
    ]
