# Generated by Django 2.1 on 2019-03-06 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maincalendar', '0002_announcement_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='maincalendar.Event'),
        ),
    ]
