# Generated by Django 2.1 on 2019-03-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincalendar', '0002_auto_20190321_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='scope',
        ),
        migrations.AddField(
            model_name='event',
            name='college',
            field=models.CharField(blank=True, choices=[('1', 'College of Engineering'), ('2', 'College of Science')], default='N/A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deg_prog',
            field=models.CharField(blank=True, choices=[('1', 'Chemical Engineering'), ('2', 'Civil Engineering'), ('3', 'Computer Science'), ('4', 'Computer Engineering'), ('5', 'Electrical Engineering'), ('6', 'Electronics Engineering'), ('7', 'Geodetic Engineering'), ('8', 'Industrial Engineering'), ('9', 'Mechanical Engineering'), ('10', 'Mining Engineering'), ('11', 'Metallurgical Engineering'), ('12', 'Materials Engineering')], default='N/A', max_length=50, null=True),
        ),
    ]
